---
layout: post
title: gazebo
---


```
lucasw@glover:~/tmp_catkin_ws$ roslaunch rrbot_gazebo rrbot_world.launch
... logging to /home/lucasw/.ros/log/300a352e-ecb1-11e5-b860-00dbdf11ceac/roslaunch-glover-2577.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
xacro.py is deprecated; please use xacro instead
started roslaunch server http://127.0.0.1:40778/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /rosdistro: jade
 * /rosversion: 1.11.16
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://127.0.0.1:11311

core service [/rosout] found
process[gazebo-1]: started with pid [2621]
process[gazebo_gui-2]: started with pid [2635]
process[urdf_spawner-3]: started with pid [2647]
log4cxx: Could not read configuration file [/home/lucasw/.ros/rosconsole.config].
log4cxx: Could not read configuration file [/home/lucasw/.ros/rosconsole.config].
Traceback (most recent call last):
  File "/home/lucasw/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/spawn_model", line 31, in <module>
    import tf.transformations as tft
  File "/opt/ros/jade/lib/python2.7/dist-packages/tf/__init__.py", line 29, in <module>
    from listener import TransformListener, TransformerROS
  File "/opt/ros/jade/lib/python2.7/dist-packages/tf/listener.py", line 30, in <module>
    roslib.load_manifest(PKG)
  File "/opt/ros/jade/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/jade/lib/python2.7/dist-packages/roslib/launcher.py", line 93, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 164, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 208, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/manifest.py", line 393, in parse_manifest_file
    _static_rosdep_view = init_rospack_interface()
  File "/usr/lib/python2.7/dist-packages/rosdep2/rospack.py", line 58, in init_rospack_interface
    lookup = _get_default_RosdepLookup(Options())
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 127, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 607, in create_default
    sources = load_cached_sources_list(sources_cache_dir=sources_cache_dir, verbose=verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 508, in load_cached_sources_list
    return parse_sources_data(cache_data, origin=cache_index, model=model)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 366, in parse_sources_data
    raise InvalidData("line:\n\t%s\n%s"%(line, e), origin=origin)
rosdep2.core.InvalidData: line:
  yaml https://github.com/ros/rosdistro/raw/master/rosdep/osx-homebrew.yaml osx
unsupported pickle protocol: 4
log4cxx: Could not read configuration file [/home/lucasw/.ros/rosconsole.config].
[ INFO] /gazebo /home/lucasw/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/src/gazebo_ros_api_plugin.cpp:155 : Finished loading Gazebo ROS API Plugin.
[ INFO] /gazebo /tmp/binarydeb/ros-jade-roscpp-1.11.16/src/libros/service.cpp:80 : waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[urdf_spawner-3] process has died [pid 2647, exit code 1, cmd /home/lucasw/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/spawn_model -urdf -model rrbot -param robot_description __name:=urdf_spawner __log:=/home/lucasw/.ros/log/300a352e-ecb1-11e5-b860-00dbdf11ceac/urdf_spawner-3.log].
log file: /home/lucasw/.ros/log/300a352e-ecb1-11e5-b860-00dbdf11ceac/urdf_spawner-3*.log
```

Gazebo loads successfully

On my other systems gazebo is 5.0.1, but here it is 5.1.0?
Is something wrong with urdf_spawner?

No it is something wrong with importing tf.transformations - cannot do that from a python shell.

Cannot import tf either.

   sudo apt-get install --reinstall ros-jade-tf-conversions

Still does not work.

But it works fine in a different user on same system.

Look to .bashrc differences- still nothing.
